.TH caur 1 2023-01-08

.SH NAME
caur \- AUR Helper written in C

.SH SYNOPSIS
\fIcaur\fR <operation> [targets]

.SH DESCRIPTION
caur is a simple AUR helper, used to install packages from the AUR with Makepkg.

.SH OPTIONS
.TP
.B \-S
Install package

.TP
.B \-R
Remove package

.TP
.B \-C
Clear package cache (can be run without specifying packages)
.TP

.B \-h \-\-help
Prints help info

.SH SEE ALSO
.BR makepkg(8),
.BR PKGBUILD(8)

.SH BUGS
Report bugs by sending me an email (preffered) or by reporting an issue on the GitHub page (https://github.com/mxdixyz/caur)

.SH Author
Written by Madison Lynch <madi@mxdi.xyz>